[package]
name = "lark"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = { version = "0.29", features = ["event-stream"] }
dirs = "5"
futures = "0.3"
rhai = "1"
ropey = "1.4"
tokio = { version = "1", features = ["full"] }
